version: '2'
services:
  jhipster21points-app:
    image: jhipster21points
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster21points-postgresql:5432/jhipster21points
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipster21points-postgresql:
    extends:
      file: postgresql.yml
      service: jhipster21points-postgresql
