version: '2'
services:
  jhipster21points-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/jhipster21points/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhipster21points
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
